apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
# images:
#   - name: parksmap-web/image
#     newName: image-registry.openshift-image-registry.svc:5000/aussie-project/parksmap-web
#     newTag: 464cfd7f59f1912afb0c6fe556201dfb9a9f9909
